[tool.poetry]
name = "lime-etl"
version = "0.1.9"
description = "Simple ETL job runner"
authors = ["Mark Stefanovic"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "^1.3.19"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
