[tool.poetry]
name = "syngle"
version = "0.4.0"
description = "Simple package implementing the Singleton pattern as a metaclass and decorator."
authors = ["Valentin Calomme <dev@valentincalomme.com>"]
homepage = "https://valentincalomme.github.io/syngle/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/valentincalomme/syngle"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
bump2version = "^1.0.0"
coverage = "^5.3"
coverage-badge = "^1.0.1"
darglint = "^1.5.4"
docstr-coverage = "^1.2.0"
flake8 = "^3.8.3"
flake8-docstrings = "^1.5.0"
ipython = "^7.18.1"
isort = "^5.5.3"
mkdocs = "^1.1.2"
mkdocs-markdownextradata-plugin = "^0.1.7"
mkdocs-material = "^6.0.1"
mkdocstrings = "^0.13.6"
mypy = "^0.782"
pre-commit = "^2.7.1"
pytest = "^6.1.0"
pytest-cov = "^2.10.1"
seed-isort-config = "^2.2.0"

[tool.black]
line-length = 120
target-version = ['py37']

[tool.coverage.run]
include = ["syngle/*.py"]

[tool.isort]
known_third_party = []

[tool.pytest.ini_options]
junit_family = "xunit2"
testpaths = ["tests/", "syngle/"]
addopts = ["--doctest-modules", "--cov"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
