[tool.poetry]
name = "nbjuniper"
version = "0.2.5"

authors = ["Michael Ashton <ashtonmv@gmail.com>"]
license = "MIT"

description = "Convert Jupyter Notebooks into runnable HTML files with Juniper (https://github.com/ines/juniper)."
readme = 'README.md'

repository = "https://github.com/ashtonmv/nbjuniper"
homepage = "https://github.com/ashtonmv/nbjuniper"

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3.1"
markdown = "^3.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
nbjuniper = 'nbjuniper.cli:main'
